# Generated by Django 5.0.1 on 2024-11-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0002_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default='Unknown', max_length=40),
        ),
        migrations.AddField(
            model_name='student',
            name='specialization',
            field=models.CharField(default='unknown', max_length=40),
        ),
    ]
